### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#1]
As a **user** I can **view a navbar from every page so that i can navigate easily between pages** so that **received benefit**
***

### Tasks
- [ ] Create Navbar component
- [ ] Add links and create category links on created pages
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] Have Search functionality to each page on the website

***
