### ISSUE TITLE
USER STORY: Delete a Trip Post

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#10]
As a **user** I can **delete a trip/ post** so that **no one can view the trip /post**
***

### Task
- [ ] Create delete functionality
- [ ] Add delete button to page.
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] Able to delete trip pictures/ posts

***
