### ISSUE TITLE
USER STORY: Search trips/posts/ profiles

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#11]
As a **user** I can **search uploaded trips and posts for specific trips/ users/ keywords** so that **i can find specific details i am interested in**
***

### Task
- [ ] Create search field and function
- [ ] Add search field to main page
- [ ] ensure field is visible on all pages of the site

***

### ACCEPTANCE CRITERIA
- [ ] users to successfully search.

***
