### ISSUE TITLE
USER STORY: View all posted trips

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#12]
As a **user** I can **view all the most recent trips** so that **the most recent created trips are shown first so that i am up to date with the newest content**
***

### Task
- [ ] Create variable for usestate and useeffect
- [ ] create a try and catch for the data
- [ ] call fetchData on component mount
- [ ] test out functionality

***

### ACCEPTANCE CRITERIA
- [ ] Able to infinite scroll on trip posts

***
