### ISSUE TITLE
USER STORY: Like/ unlike trips

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#13]
As a **logged in user** I can **demonstrate the trips I like/ unlike** so that **show my enjoyment of the shared pictures**
***

### Task
- [ ] create the like function and button
- [ ] test the functionality

***

### ACCEPTANCE CRITERIA
- [ ] Be able to like/unlike a trip

***
