### ISSUE TITLE
USER STORY: View Trip comments

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#14]
As a **user** I can **view the trips/ posts** so that **i can read the shared comments about the trip**
***

### Task
- [ ] create comment function
- [ ] ensure it is visible on the page
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] able to view comments on a trip

***
