### ISSUE TITLE
USER STORY: Create Comment

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#15]
As a **logged in user** I can **add comments to a post** so that **i can share my thoughts about the trip**
***

### Task
- [ ] create comments.js page
- [ ] ensure it is visible on the trip page
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] Able to create and view a comment on the trip

***
