### ISSUE TITLE
USER STORY:Edit Comment

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#16]
As a **user** I can **i can edit my comments** so that **i can fix any mistakes or update my existing comment**
***

### Task
- [ ] create a post edit form page
- [ ] Add link to page to app.js 
- [ ] confirm functionality is working

***

### ACCEPTANCE CRITERIA
- [ ] be able to edit my comments

***
