### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#17]
As a **user** I can **delete my comment** so that **remove any of my comments when i want**
***

### Task
- [ ] define functionality to delete comment
- [ ] test functionality works

***

### ACCEPTANCE CRITERIA
- [ ] be able to delete a comment

***
