### ISSUE TITLE
USER STORY: Create Profile Page

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#18]
As a **user** I can **add a picture and bio** so that **i can tell people about my self and sailing likes**
***

### Task
- [ ] Ensure the profile picture is visible
- [ ] ensure Bio can be added

***

### ACCEPTANCE CRITERIA
- [ ] be able to view the profile, profile avatar and bio

***
