### ISSUE TITLE
USER STORY: User Profile stats

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#19]
As a **user** I can **view stats on my profile use** so that **gain insight into my bio, the number of trips i have likes, people i have followed**
***

### Task
- [ ] Define the stats to show on the profile
- [ ] Ensure the stats are visible on the profile
- [ ] test the stats move.. ie when another profile is followed, followed + 1

***

### ACCEPTANCE CRITERIA
- [ ] A stats search when increases / decreases when changed .

***
