### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#2]
As a **user** I can **create a new account** so that **I can access the website and use all of the features**
***

### Task
- [ ] Create an account sign up page
- [ ] Create a link to sign up page on Navbar/ main apps.js page
- [ ] link to backend api
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] user has functionality to create account and sign up

***
