### ISSUE TITLE
USER STORY:follow/ unfollow

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#20]
As a **logged in user** I can **follow/ unfollow another member** so that **i can see/ remove any other content from other members trip feeds.**
***

### Task
- [ ] Implement a follow/ unfollow function
- [ ] ensure its visible when looking at members profiles
- [ ] when follow/ unfollow ensure stats change.

***

### ACCEPTANCE CRITERIA
- [ ] having ability to follow/ unfollow
- [ ] stats section changes

***
