### ISSUE TITLE
USER STORY: Edit Profile data

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#21]
As a **user** I can **change details on my profile** so that **i can change the data i share with other members**
***

### Task
- [ ] create a profile edit form
- [ ] ensure the link is visible on app. js page

***

### ACCEPTANCE CRITERIA
- [ ] to be able to edit profile pic and bio successfully

***
