### ISSUE TITLE
USER STORY:Update username and password

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#22]
As a **user** I can **update my username and password** so that **i can keep my profile secure**
***

### Task
- [ ] Create username form
- [ ] create a password form
- [ ] ensure visible on the site

***

### ACCEPTANCE CRITERIA
- [ ] Be able to see link to change username/ password
- [ ] Be able to change password and username

***
