### ISSUE TITLE
USER STORY: Sign In

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#3]
As a **new user** I can **sign in to the app** so that **i can access the website functions**
***

### Task
- [ ] Create Sign Up page and functionality. 
- [ ] Add sign in form to Navbar/ apps.js page
- [ ] test out functionality

***

### ACCEPTANCE CRITERIA
- [ ] User with a username and password can sign in and out

***
