### ISSUE TITLE
USER STORY: signed in status

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#4]
As a **user** I can **clearly see if i am logged into/ out of the website** so that **i can log in if i need to**
***

### Task
- [ ] Create a sign out link on apps.js
- [ ] Add sign out button to navbar
- [ ] test functionality to ensure clear for user when signed in/ signed out 
***

### ACCEPTANCE CRITERIA
- [ ] clear for user when signed in/ signed out 

***
