### ISSUE TITLE
USER STORY: Create a trip/ post

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#6]
As a **user** I can **create a trip/ post** so that **i can share my pictures of a recent Yacht club trip**
***

### Task
- [ ] Create a page to add new trips
- [ ] create trip create form function
- [ ] ensure that errors are flagged and defined
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] Functionality successfully works

***
