### ISSUE TITLE
USER STORY: View a single Trip/ Post

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#7]
As a **user** I can **view the posted pictures of a single trip picture** so that **I can learn more about it**
***

### Task
- [ ] create trip detail page
- [ ] link to signed in user page.
- [ ] fetch the trips while define/ catch the errors
- [ ] test out functionality

***

### ACCEPTANCE CRITERIA
- [ ] Able to post pictures of the sailing trips.

***
