### ISSUE TITLE
USER STORY: Like a trip /post

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#8]
As a **user** I can **like a share Trip picture** so that **i can share my enthusiasm for the picture**
***

### Task
- [ ] create a like view.
- [ ] Implement the like functionality on the pictures.
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] Be able to like the picture

***
