### ISSUE TITLE
USER STORY: Edit a trip /post

### ISSUE THREAD

**Issue by benjackson3811** [benjackson3811/yacht-club#9]
As a **user** I can **edit a trip/ post title or description** so that **i can update the details if needed**
***

### Task
- [ ] create an edit trip page.
- [ ] create trip edit function
- [ ] ensure link is on app.js page
- [ ] test functionality

***

### ACCEPTANCE CRITERIA
- [ ] Ability to edit a trip picture or description

***
